name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Cache Maven and Gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/.gradle
        key: ${{ runner.os }}-build-${{ hashFiles('**/*.gradle*') }}

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Prepare deployment artifacts
      run: |
        mkdir -p before-deploy
        cp scripts/*.sh before-deploy/
        cp appspec.yml before-deploy/
        cp build/libs/*.jar before-deploy/
        cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
        cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
        mv before-deploy/before-deploy.zip deploy/foreverpet.zip # deploy로 zip파일 이동

    - name: Deploy to S3
      uses: aws-actions/aws-s3-deploy@v3
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        region: ap-northeast-2
        bucket: foreverpets3
        local-dir: deploy
        wait-until-deployed: true

    - name: Deploy to CodeDeploy
      uses: aws-actions/aws-codedeploy@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        region: ap-northeast-2
        bucket: foreverpets3
        key: foreverpet.zip
        bundle-type: zip
        application-name: foreverpet
        deployment-group: foreverpet-group
        wait-until-deployed: true

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: CI Build Notification
        body: The CI build has completed successfully.
        to: cmong0516@gmail.com
        from: ${{ secrets.EMAIL_USERNAME }}
